import { AuthLayout, MainLayout } from '@/components/Layouts';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Suspense } from 'react';
import './globals.css';

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin', 'vietnamese'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={` ${interSans.className} bg-background text-typography antialiased`}
      >
        <MainLayout>
          <Suspense fallback="loading...">
            <AuthLayout>{children}</AuthLayout>
          </Suspense>
        </MainLayout>
      </body>
    </html>
  );
}
